create table shipment (
	id INT,
	departurePlace VARCHAR(50),
	arrivalPlace VARCHAR(50),
	finaldate DATE,
	transportType VARCHAR(10),
	capacity INT,
	client_id INT
);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (1, '7330 Eliot Junction', '46 Springview Point', '11/24/2017', 'water', 71, 68);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (2, '38640 Manitowish Hill', '0723 Hoffman Place', '7/18/2018', 'overweight', 73, 10);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (3, '623 Dryden Hill', '93302 David Point', '2/4/2018', 'land', 47, 26);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (4, '4 Lawn Drive', '5 Novick Alley', '1/19/2018', 'overweight', 34, 38);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (5, '3 1st Park', '36 Donald Avenue', '4/30/2018', 'land', 20, 59);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (6, '74271 Reindahl Avenue', '8419 Kensington Way', '8/2/2018', 'air', 82, 64);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (7, '1 Helena Avenue', '4 Rockefeller Parkway', '10/22/2017', 'water', 88, 33);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (8, '78479 Cardinal Park', '15930 Schurz Lane', '11/2/2017', 'air', 18, 18);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (9, '195 Debs Place', '27450 Hoffman Trail', '7/20/2018', 'air', 57, 68);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (10, '3 Muir Junction', '037 Linden Hill', '12/17/2017', 'overweight', 95, 12);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (11, '2 West Circle', '20 Oak Lane', '12/23/2017', 'air', 69, 78);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (12, '31594 Hovde Avenue', '7 Namekagon Lane', '7/9/2018', 'overweight', 29, 77);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (13, '28126 Hintze Hill', '1 Fisk Place', '12/26/2017', 'overweight', 53, 47);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (14, '92770 Pepper Wood Road', '75 Mccormick Trail', '12/11/2017', 'air', 3, 71);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (15, '362 Corben Trail', '4 Eastwood Street', '12/22/2017', 'air', 6, 53);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (16, '39643 Rockefeller Hill', '559 Roth Lane', '1/16/2018', 'land', 45, 45);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (17, '3739 Sage Trail', '124 Bayside Lane', '1/6/2018', 'water', 100, 56);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (18, '34 Northport Alley', '06405 Dwight Trail', '10/25/2017', 'land', 67, 91);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (19, '380 Bartillon Terrace', '5805 Loeprich Park', '8/20/2018', 'overweight', 96, 82);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (20, '653 8th Lane', '04030 Orin Trail', '11/1/2017', 'overweight', 41, 37);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (21, '86039 New Castle Terrace', '60 Pawling Park', '8/24/2018', 'overweight', 32, 85);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (22, '40 Dawn Plaza', '13925 Marquette Road', '12/9/2017', 'air', 86, 72);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (23, '97086 Becker Court', '8976 Carey Plaza', '3/11/2018', 'water', 94, 14);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (24, '75 Oak Way', '653 Esker Parkway', '6/7/2018', 'overweight', 88, 61);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (25, '90 Anderson Street', '6673 Elka Lane', '8/7/2018', 'land', 25, 66);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (26, '51039 Randy Point', '57 Thierer Avenue', '12/9/2017', 'overweight', 75, 38);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (27, '4 Delaware Circle', '2019 Everett Junction', '7/26/2018', 'land', 20, 67);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (28, '008 Cardinal Terrace', '8133 Tomscot Street', '5/24/2018', 'air', 6, 20);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (29, '0078 Clyde Gallagher Plaza', '25672 Bultman Place', '4/2/2018', 'overweight', 50, 39);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (30, '968 Oriole Court', '20 Westerfield Junction', '11/9/2017', 'land', 50, 54);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (31, '0 Tennessee Place', '40335 Maywood Drive', '10/8/2017', 'air', 2, 71);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (32, '71776 Amoth Crossing', '06841 Ludington Plaza', '12/21/2017', 'overweight', 74, 55);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (33, '90080 Katie Pass', '0071 Mayer Avenue', '12/7/2017', 'overweight', 7, 76);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (34, '3 Clarendon Crossing', '74275 Commercial Crossing', '5/18/2018', 'water', 4, 20);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (35, '20 Butternut Point', '14 Johnson Center', '6/28/2018', 'air', 95, 10);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (36, '97916 Melrose Terrace', '616 Dottie Road', '3/23/2018', 'land', 35, 23);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (37, '537 Walton Alley', '524 Michigan Circle', '5/15/2018', 'overweight', 75, 27);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (38, '6 Gale Crossing', '0 Jay Lane', '5/26/2018', 'overweight', 23, 45);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (39, '2460 Blackbird Center', '46543 Hagan Trail', '2/10/2018', 'water', 21, 3);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (40, '0833 Warrior Terrace', '3853 Mccormick Junction', '12/30/2017', 'overweight', 10, 51);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (41, '950 Novick Park', '47 Lake View Court', '11/4/2017', 'overweight', 4, 71);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (42, '68 Summerview Street', '3 Green Ridge Terrace', '2/1/2018', 'overweight', 48, 45);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (43, '66 Heffernan Junction', '10907 Steensland Court', '8/13/2018', 'water', 71, 66);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (44, '8 School Street', '15722 Derek Alley', '9/27/2017', 'water', 32, 14);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (45, '6 Bartelt Way', '075 Donald Pass', '7/6/2018', 'water', 42, 93);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (46, '05 Wayridge Alley', '4700 Walton Center', '9/29/2017', 'air', 72, 68);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (47, '0743 Gulseth Alley', '06142 Gateway Drive', '1/15/2018', 'air', 18, 79);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (48, '74939 Sherman Trail', '16558 Sugar Hill', '1/5/2018', 'water', 72, 34);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (49, '260 Rieder Circle', '9718 Lakewood Avenue', '6/4/2018', 'water', 82, 6);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (50, '2 Sycamore Drive', '39457 Eastwood Parkway', '8/14/2018', 'land', 9, 58);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (51, '04 Hagan Circle', '025 Golf Course Road', '12/12/2017', 'land', 33, 30);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (52, '1309 Bowman Trail', '72 Blue Bill Park Drive', '6/26/2018', 'water', 83, 82);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (53, '5 Prairieview Junction', '56 Declaration Terrace', '10/15/2017', 'land', 21, 97);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (54, '79642 Lighthouse Bay Avenue', '2889 Basil Drive', '12/28/2017', 'water', 90, 75);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (55, '51 Butterfield Way', '0 Ronald Regan Parkway', '10/16/2017', 'air', 48, 81);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (56, '67 Dunning Lane', '96 Hermina Hill', '11/15/2017', 'water', 95, 15);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (57, '4829 Dawn Court', '4 Harper Avenue', '9/7/2017', 'water', 82, 77);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (58, '0 Carey Junction', '18 Center Plaza', '9/8/2017', 'land', 4, 35);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (59, '6763 Spohn Point', '442 Manley Street', '6/27/2018', 'water', 75, 17);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (60, '1135 Park Meadow Road', '39068 Bayside Junction', '4/29/2018', 'air', 92, 74);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (61, '73 Randy Street', '73464 Pepper Wood Drive', '5/1/2018', 'land', 31, 82);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (62, '359 Amoth Point', '65831 Emmet Alley', '1/21/2018', 'overweight', 61, 65);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (63, '5780 Armistice Center', '95 Trailsway Circle', '4/1/2018', 'land', 48, 40);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (64, '9 Utah Point', '040 Forster Junction', '12/13/2017', 'water', 96, 32);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (65, '939 Kenwood Terrace', '41751 Johnson Trail', '8/12/2018', 'land', 90, 22);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (66, '29 Debra Road', '38478 Marcy Place', '10/9/2017', 'air', 60, 4);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (67, '99638 Karstens Plaza', '397 Vahlen Alley', '11/16/2017', 'overweight', 43, 77);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (68, '07 Dexter Drive', '76536 Westend Park', '11/28/2017', 'water', 22, 10);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (69, '08 Ohio Center', '34 Reinke Avenue', '10/22/2017', 'land', 79, 5);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (70, '41 Buell Terrace', '7 Crest Line Terrace', '2/27/2018', 'land', 98, 39);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (71, '9270 Esch Crossing', '337 Schurz Alley', '3/26/2018', 'overweight', 20, 84);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (72, '4464 Cardinal Terrace', '3943 Pond Parkway', '2/21/2018', 'air', 79, 96);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (73, '11 Logan Street', '20 Shoshone Place', '4/20/2018', 'land', 7, 9);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (74, '7156 1st Point', '15 Brown Plaza', '10/16/2017', 'overweight', 97, 1);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (75, '519 Victoria Trail', '4576 Hermina Lane', '1/3/2018', 'land', 57, 61);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (76, '19 Graceland Road', '70042 Little Fleur Trail', '11/2/2017', 'overweight', 55, 71);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (77, '8 Dwight Circle', '132 Melby Parkway', '9/8/2017', 'air', 23, 25);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (78, '514 Fairview Avenue', '781 Arrowood Drive', '10/14/2017', 'land', 55, 71);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (79, '58 Westerfield Point', '3198 Carberry Court', '9/16/2017', 'water', 67, 26);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (80, '4153 Veith Center', '16 Boyd Street', '8/2/2018', 'water', 31, 36);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (81, '60608 Crownhardt Park', '01 Manufacturers Lane', '12/15/2017', 'air', 86, 51);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (82, '5289 Service Plaza', '89579 Buhler Plaza', '6/19/2018', 'overweight', 86, 40);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (83, '313 Swallow Junction', '139 Artisan Trail', '7/22/2018', 'air', 21, 28);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (84, '08934 Briar Crest Way', '798 Fieldstone Plaza', '8/21/2018', 'land', 64, 82);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (85, '5938 Pepper Wood Circle', '9 Havey Park', '6/10/2018', 'overweight', 32, 30);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (86, '2 Russell Road', '26084 Red Cloud Center', '5/8/2018', 'air', 84, 51);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (87, '0151 Di Loreto Alley', '56 Briar Crest Junction', '9/27/2017', 'land', 45, 88);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (88, '26898 Nelson Terrace', '652 Hoepker Crossing', '7/31/2018', 'water', 71, 98);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (89, '9 2nd Avenue', '39984 Amoth Point', '12/12/2017', 'air', 21, 67);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (90, '3 Lakeland Alley', '8 Meadow Vale Center', '9/10/2017', 'overweight', 28, 73);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (91, '16470 Gale Parkway', '55 Warner Park', '10/27/2017', 'air', 82, 16);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (92, '7 Monument Lane', '721 Brown Trail', '4/4/2018', 'overweight', 2, 70);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (93, '9 Eliot Crossing', '6 Mandrake Center', '3/2/2018', 'overweight', 30, 91);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (94, '593 Sugar Park', '845 Fallview Plaza', '12/31/2017', 'water', 26, 50);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (95, '759 Shopko Place', '725 Lotheville Avenue', '1/17/2018', 'air', 81, 80);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (96, '4959 Cherokee Circle', '653 Emmet Point', '8/13/2018', 'overweight', 8, 73);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (97, '394 Anderson Avenue', '65 Hanover Parkway', '11/13/2017', 'overweight', 76, 33);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (98, '54976 Saint Paul Place', '34674 Evergreen Parkway', '10/31/2017', 'overweight', 24, 29);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (99, '382 Linden Lane', '40943 Mallard Lane', '6/28/2018', 'air', 57, 25);
insert into shipment (id, departurePlace, arrivalPlace, finaldate, transportType, capacity, client_id) values (100, '4 Barnett Park', '61485 Dryden Plaza', '9/15/2017', 'overweight', 37, 95);*/